apiVersion: v1
kind: Pod
metadata:
  name: pod-errors
  labels:
    app: pod-errors
spec:
  restartPolicy: OnFailure
  containers:
    - name: helloworld
      image: monokle-helloworld:1.5
      command: ["sh", "-c", "echo I am running as user $(id -u)"]
      securityContext:
        capabilities:
          add: [SYS_ADMIN]
