apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    env: dev
spec:
  replicas: 6
  template:
    spec:
      containers:
        - name: nginx
          env:
            - name: DEV
              value: BAR
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
