apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-deployment
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web-app
  template:
    metadata:
      labels:
        app: nginx-web-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          resources:
            limits:
              memory: 1G
              CPU: 250M
          ports:
            - containerPort: 80
